spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: github.clientId
            clientSecret: github.secret
          google:
            client-id: google.clientId
            client-secret: google.secret